### ISSUE TITLE
Error when disabling `hidden` option; Error when seting `%` in `shada`

### ISSUE THREAD

**Issue by oredaze** [matbme/JABS.nvim#26]
neovim 0.7.0

I experience a couple of situations where JABS fails to launch properly.
- One is when I have disabled the `hidden` nvim option.
- The other is when I set `%` in the `shada` option. `%` makes it so that when I launch nvim without a file it remembers the buffers from previous time. Of course I have to launch it like that to produce the problem.
The error looks like this:
![2022-06-03-175606](https://user-images.githubusercontent.com/51076873/171886699-49f63360-c1e1-459b-9d20-35c0d4806ef8.png)

`api.nvim_buf_add_highlight` somehow fails to set the highlights and that brakes the rest of JABS. When I remove that function and related things, JABS seems to work fine (but the text disappears of course).
I don't know enough about coding to tell you more.

**Comment by oredaze** [comment]
So the first issue still persists for me. It also gives the same error message.

For the second, unfortunately it's only half way fixed. When I launch JABS in the aforementioned way it no longer displays errors, but when I try to go to a buffer it gives me `Buffer number not found!`. Then if I focus that buffer with normal means like `:b2` then that buffer starts being recognized. I have to do that for each individual one...

**Comment by matbme** [comment]
The second issue should be fixed now.

Could you output your full shada config?

**Comment by oredaze** [comment]
It is fixed now. Thank you so much for the good work. Here is my shada config anyway (I have init.lua):
`vim.opt.shada = "%,\"35,'20,f1,<32,:30,/5,h,n~/.config/nvim/main.shada"`
I hope we can see the first bug fixed some day. I have tested with empty config file, only `vim.opt.hidden = false`, so it's not on my end.

**Comment by matbme** [comment]
Ok, I see what's going on. The alternate buffer when hidden=false is labelled only as `#` instead of `#h`, which didn't have a corresponding option in the highlights table. Problem should be fixed now.

Please let me know if everything's running fine :)

**Comment by oredaze** [comment]
Everything is running fine! Thanks.
I love your plugin. Simple but powerful design.
