### ISSUE TITLE
Error when file name has certain characters

### ISSUE THREAD

**Issue by oredaze** [matbme/JABS.nvim#27]
I'm sorry to bother you again, but I have found an other bug:
When opening buffers with file names that have certain characters in them I get the following:
![s](https://user-images.githubusercontent.com/51076873/172629748-f0b2f9f7-0d7c-429d-bb72-d2ad23148ef4.png)
I have tested with some characters (not that many) and looks like `-`, `+`, `%` produce this problem. There could be more, but that should be enough to prove the point.
`-` is a very common file name character...

**Comment by matbme** [comment]
Hi, no worries, that's what issues are for :)

This was a tricky one to nail down, but should be fixed now.
