### ISSUE TITLE
Getting this error while opening JABS!

### ISSUE THREAD

**Issue by devdesignersid** [matbme/JABS.nvim#3]
```
E5108: Error executing lua /Users/user/.vim/plugged/JABS.nvim/lua/jabs.lua:100: attempt to concatenate local 'symbol' (a │
nil value)   
```

If i press enter it takes me to an empty pane.

**Comment by matbme** [comment]
Hi!

Can you send a screenshot of the buffers that appear when you use the `:ls` command?

**Comment by devdesignersid** [comment]
![Screenshot 2021-06-07 at 9 26 12 PM](https://user-images.githubusercontent.com/68458106/121051351-032b5680-c7d7-11eb-95bb-ee3c8fbbf759.png)

**Comment by matbme** [comment]
I'm not sure why the first file in your `:ls` command has no attributes, but I merged a line to check if symbol is null. It should work now
