### ISSUE TITLE
Closing the preview does not take the cursor back to JABS

### ISSUE THREAD

**Issue by AZanellato** [matbme/JABS.nvim#30]
First off, this plugin is wonderful, great job!

I was trying out it and noticed that the cursor doesn't go back to JABS the preview is closed, instead the cursor goes back to the first open pane.

Am I missing something?

**Comment by matbme** [comment]
Hi, thanks for the comments!

Apparently some previous change broke the preview window and I missed it. It should be fixed now. 

You can now exit the preview window by pressing `q` or by navigating to some other window (with either the mouse or keyboard). If the newly selected window is JABS' main window, it should stay open,
