### ISSUE TITLE
E5108: Error executing lua ...share/nvim/site/pack/packer/start/JABS.nvim/lua/jabs.lua:269: assertion failed! 

### ISSUE THREAD

**Issue by hrqmonteiro** [matbme/JABS.nvim#45]
When i open i got this error:

```
E5108: Error executing lua ...share/nvim/site/pack/packer/start/JABS.nvim/lua/jabs.lua:269: assertion failed!
stack traceback:
        [C]: in function 'assert'
        ...share/nvim/site/pack/packer/start/JABS.nvim/lua/jabs.lua:269: in function 'updatePos'
        ...share/nvim/site/pack/packer/start/JABS.nvim/lua/jabs.lua:611: in function 'open'
        [string ":lua"]:1: in main chunk
```

![Screenshot from 2023-01-09 00-13-23](https://user-images.githubusercontent.com/17055027/211235563-1fc7dc1a-ae67-45cf-82b1-3a37b0835e8a.png)

**Comment by JacobAshoo** [comment]
If you wrote the setup inside a file other than init.lua, make sure to use(PATH_TO_JABS_CONFIG) in your init.lua. I had the same issue.

**Comment by sentientmachin3** [comment]
I'm getting the same error, but this happens if I run `JABSopen` with only a single Netrw buffer.

**Comment by jeff-dh** [comment]
I'd still like to see your config.

The assert that fails says:

```lua
assert(type(M.conf.position) == "table")
```

So at least on the first glance it seems pretty obvious that there must be some issue concerning the configuration -- even though your config might be correct!

**Comment by jeff-dh** [comment]
@sentientmachin3 are you sure that you have **exactly** the same error? Is the line number the same or is it possible that your ran into a different assert?

**Comment by sentientmachin3** [comment]
I confirm it was the same exact error, but somehow I can't trigger it anymore as it happened before. I'll update as soon as I discover more.
My config was the vanilla, I only changed the border style to the rounded ones.
