### ISSUE TITLE
Autocmd for automatic centering of window doesn't work when jumping buffers with JABS

### ISSUE THREAD

**Issue by mBaratta96** [matbme/JABS.nvim#50]
Hello, thanks for the wonderful plugin.

I have an autocommand that center the window each time I switch buffer:
```lua
vim.api.nvim_create_autocmd("BufWinEnter", {
	pattern = "*",
	callback = function()
		vim.cmd("normal! zz")
	end,
})
```
Which works every time I use `bnext` and `brev`, but it doesn't when I jump with JABS.

Can you please give me a hand on this? I have been struggling for quite some time.

Keep up with the excellent work!

**Comment by jeff-dh** [comment]
Checkout expJABS (https://github.com/jeff-dh/expJABS.nvim).

I just tested your snippet and it seems to be working with expJABS.

**Comment by mBaratta96** [comment]
I gave another look at the source code and I found [this](https://github.com/matbme/JABS.nvim/blob/b6dbd1a3e1b8cef3d6ebfafe96c2230ca341b65f/lua/jabs.lua#L18). So I added this to my config:
```lua
require("jabs").openOptions.window = "b%s | normal! zz"
```

I think it would be nice to have the whole `openOptions` configurable.

**Comment by jeff-dh** [comment]
> I think it would be nice to have the whole `openOptions` configurable.

The latest expJABS head supports it now.
