### ISSUE TITLE
Switch to buffers with number

### ISSUE THREAD

**Issue by rambip** [matbme/JABS.nvim#6]
This is a feature request:
It would be really nice if the buffers in the list were numbered (with number that make sense, 0 to n-1 for exemple).

And you just would need to type the corresponding number to switch.

I didn't see any plugin that do that, it would be really cool !

**Comment by rambip** [comment]
Oh sorry I didn't see the item in the TODO list !
So I'm waiting for it now...

And this is unrelated but I'm not sure I would like buffers previews ...

**Comment by matbme** [comment]
Hey! Just pushed a commit that adds this functionality. You should now be able to switch to or split a buffer by typing its number before a command.
