### ISSUE TITLE
Shorten the path or enlarge the window to show the full file name

### ISSUE THREAD

**Issue by QiBaobin** [matbme/JABS.nvim#7]
Thanks for the great tool,  it's hard to figure out what buffers are when their file name are long, can we shorten the path part like a lot of buffline plugins does to ensure their file name could be seen, or size the window based on the content?
<img width="539" alt="Screen Shot 2021-07-07 at 11 37 05 AM" src="https://user-images.githubusercontent.com/7072/124696453-b2af3200-df17-11eb-8e8c-71d576db2bc4.png">

**Comment by matbme** [comment]
Took a while to figure this one out without having to rewrite the line formatting logic, but just pushed a commit that changes the truncation logic to add the "..." in the beginning of the file name :D

**Comment by QiBaobin** [comment]
Confirmed, it works now, thanks!
