### ISSUE TITLE
Calling :JABSOpen when there is already a JABS window opens another JABS window

### ISSUE THREAD

**Issue by zeertzjq** [matbme/JABS.nvim#9]
Calling `:JABSOpen` when there is already a JABS window opens another JABS window, and this can cause some weird effects. If `:JABSOpen` is called multiple times in a non-floating window, multiple JABS windows are opened in the same position. If `:JABSOpen` is called inside a JABS window (which can happen if a keybinding mapped to `:JABSOpen` is pressed multiple times), another JABS window is opened in a position one line and one column off from the original position.
Maybe `:JABSOpen` can be changed to something that toggles the JABS window (`:JABSToggle`)?

**Comment by zeertzjq** [comment]
1

**Comment by matbme** [comment]
Hello! Just pushed a [commit](https://github.com/matbme/JABS.nvim/commit/fc87c5c2420a17aeedf0dc189e5184d7c113801f) that addresses this problem to the `bugfix` branch. Could you configure your package manager to pull from it and test it out?



> Maybe :JABSOpen can be changed to something that toggles the JABS window (:JABSToggle)?

In the future I might add a `:JABSToggle` command, but for now I kept `:JABSOpen` as the toggle command for compatibility.

**Comment by zeertzjq** [comment]
It works. `:JABSOpen` toggles the buffer switcher.

**Comment by matbme** [comment]
Great! Bugfix branch is now merged with Main
